export const defaultMarkweaveCodeBlockLanguages = [
  "angular-html",
  "apache",
  "arduino",
  "bash",
  "c",
  "clojure",
  "cmake",
  "cpp",
  "csharp",
  "css",
  "dart",
  "diff",
  "django",
  "dockerfile",
  "elixir",
  "erb",
  "erlang",
  "fortran",
  "fsharp",
  "glsl",
  "go",
  "gradle",
  "graphql",
  "groovy",
  "handlebars",
  "haskell",
  "hjson",
  "html",
  "html-derivative",
  "http",
  "ini",
  "java",
  "javascript",
  "json",
  "json5",
  "jsonc",
  "jsonl",
  "jsonnet",
  "kotlin",
  "latex",
  "less",
  "lisp",
  "lua",
  "makefile",
  "markdown",
  "matlab",
  "mermaid",
  "nginx",
  "nix",
  "nushell",
  "objectivec",
  "ocaml",
  "perl",
  "pgsql",
  "php",
  "php-template",
  "plsql",
  "postcss",
  "powershell",
  "properties",
  "protobuf",
  "python",
  "python-repl",
  "r",
  "ruby",
  "rust",
  "scala",
  "scheme",
  "scss",
  "shell",
  "shellscript",
  "shellsession",
  "sql",
  "stylus",
  "swift",
  "toml",
  "tsx",
  "typescript",
  "twig",
  "vbnet",
  "vue-html",
  "vyper",
  "wasm",
  "xml",
  "yaml",
] as const;

export const localCodeBlockLanguageAliases = ["js", "jsx", "ts"] as const;

export const markweaveCodeBlockLanguages = [
  "text",
  ...defaultMarkweaveCodeBlockLanguages,
  ...localCodeBlockLanguageAliases,
] as const;

export type MarkweaveCodeBlockLanguage = (typeof markweaveCodeBlockLanguages)[number];

const codeBlockLanguageLabels: Record<MarkweaveCodeBlockLanguage, string> = {
  "angular-html": "Angular HTML",
  apache: "Apache",
  arduino: "Arduino",
  bash: "Bash",
  c: "C",
  clojure: "Clojure",
  cmake: "CMake",
  cpp: "C++",
  csharp: "C#",
  css: "CSS",
  dart: "Dart",
  diff: "Diff",
  django: "Django",
  dockerfile: "Dockerfile",
  elixir: "Elixir",
  erb: "ERB",
  erlang: "Erlang",
  fortran: "Fortran",
  fsharp: "F#",
  glsl: "GLSL",
  go: "Go",
  gradle: "Gradle",
  graphql: "GraphQL",
  groovy: "Groovy",
  handlebars: "Handlebars",
  haskell: "Haskell",
  hjson: "Hjson",
  html: "HTML",
  "html-derivative": "HTML derivative",
  http: "HTTP",
  ini: "INI",
  java: "Java",
  javascript: "JavaScript",
  js: "JavaScript",
  json: "JSON",
  json5: "JSON5",
  jsonc: "JSONC",
  jsonl: "JSONL",
  jsonnet: "Jsonnet",
  jsx: "JSX",
  kotlin: "Kotlin",
  latex: "LaTeX",
  less: "Less",
  lisp: "Lisp",
  lua: "Lua",
  makefile: "Makefile",
  markdown: "Markdown",
  matlab: "MATLAB",
  mermaid: "Mermaid",
  nginx: "Nginx",
  nix: "Nix",
  nushell: "NuShell",
  objectivec: "Objective-C",
  ocaml: "OCaml",
  perl: "Perl",
  pgsql: "PostgreSQL",
  php: "PHP",
  "php-template": "PHP Template",
  plsql: "PL/SQL",
  postcss: "PostCSS",
  powershell: "PowerShell",
  properties: "Properties",
  protobuf: "Protocol Buffers",
  python: "Python",
  "python-repl": "Python REPL",
  r: "R",
  ruby: "Ruby",
  rust: "Rust",
  scala: "Scala",
  scheme: "Scheme",
  scss: "SCSS",
  shell: "Shell",
  shellscript: "Shell Script",
  shellsession: "Shell Session",
  sql: "SQL",
  stylus: "Stylus",
  swift: "Swift",
  text: "Plain Text",
  toml: "TOML",
  ts: "TypeScript",
  tsx: "TSX",
  typescript: "TypeScript",
  twig: "Twig",
  vbnet: "VB.NET",
  "vue-html": "Vue HTML",
  vyper: "Vyper",
  wasm: "WebAssembly",
  xml: "XML",
  yaml: "YAML",
};

export function formatCodeBlockLanguageLabel(language: MarkweaveCodeBlockLanguage) {
  return codeBlockLanguageLabels[language];
}
