export const markweaveAiEditBehaviorContract = {
  owner: "host",
  requestScopes: ["selection", "blocks", "document"],
  supportedSelections: ["inline-text", "formatted-text", "multiple-paragraphs", "lists"],
  excludedTargets: ["code-block", "table", "cell-selection", "node-selection", "atom", "media", "view-mode"],
  proposalFormat: "markdown",
  streamingInput: "complete-accumulated-markdown",
  previewMode: "in-place-decoration-without-document-change",
  controls: ["default", "none"],
  reviewNavigation: "cyclic-hunk-navigation",
  hunkDecision: "staged-until-review-settlement",
  globalDecision: "accept-all-or-discard-all",
  acceptance: "accepted-hunks-in-one-transaction",
  conflictPolicy: "map-outside-edits-abort-target-edits",
  concurrency: "one-active-context-per-editor",
  persistence: "memory-only",
} as const;
